apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      if kubectl get secret sc -n team-lfx -o jsonpath='{.metadata.labels.lfx-mentorship}' | grep -q "kyverno"
      then 
        echo "Test failed. Label 'lfx-mentorship: kyverno' is present."
        exit 1 
      else 
        echo "Test succeeded. Label 'lfx-mentorship: kyverno' is not present."
        exit 0
      fi
